### ISSUE TITLE
ERROR: No matching distribution found for tkinter

### ISSUE THREAD

**Issue by cd109** [mldljyh/real_time_translation#1]
OS : win 10 
Python : Python 3.11.0

![image](https://github.com/mldljyh/whisper_real_time_translation/assets/17595696/d14cb08c-c87a-418f-a080-f8d0d5b37e63)

**Comment by mldljyh** [comment]
Please try the following command. 
You should use "tk" instead of "tkinter".
```
pip install tk
```

**Comment by cd109** [comment]
Thanks for your help
