### ISSUE TITLE
AssertionError: Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

### ISSUE THREAD

**Issue by cd109** [mldljyh/real_time_translation#2]
I am currently in this version, may I ask if there will be errors on your side?

SpeechRecognition  3.10.0

![image](https://github.com/mldljyh/whisper_real_time_translation/assets/17595696/1bcbb01a-7fbd-4c5b-aef7-815a03a1308b)

**Comment by mldljyh** [comment]
Do you have any input devices like a microphone? 
If you want to input sound coming from a speaker, you would need to use programs such as Stereo Mix or Voicemeeter.

**Comment by cd109** [comment]
Thanks for the reply, I accidentally deactivated my sound device myself.
